### ISSUE TITLE
Script tidak jalan

### ISSUE THREAD

**Issue by gvoze32** [officialputuid/toolsig-php#1]
Script tidak melanjutkan untuk mengecek following setelah berhasil sukses melakukan unfollow. Jika parameter [Udh Follow], script masih tetap bisa jalan, tapi setelah parameter [Sukses Unfollow] script tidak jalan lagi.

**Comment by officialputuid** [comment]
Ya Bug. Gunakan toolsig versi NodeJS

**Comment by gvoze32** [comment]
Yang NodeJS gampang kena deteksi sistem ig bang, padahal 1 target per 3 menit

**Comment by officialputuid** [comment]
Gunakan IP Indo
